#!/usr/bin/env bash

set -e

apps=(
    "alacritty"
    "git"
    "zsh"
    "tmux"
    "clojure"
    "spacemacs"
    "rust"
    "docker"
)

for app in "${apps[@]}"; do
    echo "Initializing $app"
    bash "./$app/init"

    if [[ -f "./$app/test" ]]; then
        echo "Testing $app"
        bash "./$app/test"
    fi

    echo "Finished initializing $app"
done
