#!/usr/bin/env bash

set -e

update_apt () {
    sudo apt-get update
}

install_apt_packages() {
    sudo add-apt-repository ppa:neovim-ppa/unstable

    sudo apt-get install \
        fonts-firacode \
        neovim \
        ripgrep \
        fd-find \
        locate \
        emacs \
        tmux \
        neofetch \
        tree \
        snapd

    echo "Updating default vim"
    sudo update-alternatives --install $(which vim) vim $(which nvim) 10
}

install_snap_packages () {
    sudo snap install \
        tandem
}

install_custom () {
    echo "Installing SDK Man"
    curl -s "https://get.sdkman.io" | bash
    source "$HOME/.sdkman/bin/sdkman-init.sh"
}

install_powerline_fonts () {
    echo "Updating powerline fonts"
    git clone https://github.com/powerline/fonts.git --depth=1
    cd fonts
    ./install.sh
    cd ..
    rm -rf fonts
}


make_base_dirs() {
    echo "Making directory structure"
    mkdir -p ~/backups/dotfiles/
    mkdir -p ~/workspace/
}

main() {
    update_apt
    install_apt_packages
    install_snap_packages
    install_custom
    install_powerline_fonts
    make_base_dirs
}

main "$@"
