#!/usr/bin/env bash

readonly base_dir=$(git rev-parse --show-toplevel)
readonly config_source="$base_dir/docker/daemon.json"
readonly config_dest="/etc/docker/daemon.json"

if [[ -x $(which docker) ]]
then
    echo "Docker is already installed on the system, skipping"
else
    echo "Installing Docker"
    curl -fsSL https://get.docker.com | bash
fi

if [[ -x $(which docker-compose) ]]
then
    echo "Docker compose is already installed on the system, skipping"
else
    echo "Installing Docker compose"
    sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
fi


echo "Updating docker daemon configuration"
DIFF=$(diff $config_source $config_dest)
if [[ $DIFF -ne 0 ]]
then
    sudo cp $config_source $dest
    echo "Restart the Docker daemon for changes to take effect"
fi
