#!/usr/bin/env bash

# Paths
readonly base_dir=$(git rev-parse --show-toplevel)
readonly tmux_path="$HOME/.tmux/plugins/tpm"
readonly nord_path="$HOME/.tmux/themes/nord-tmux"

# tpm
if [[ -d "$tmux_path" ]]
then
    echo "TPM already installed, skipping"
else
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

# themes & plugins
if [[ -d "$nord_path" ]]
then
    echo "Nord tmux theme already installed, skipping"
else
    echo "Installing Nord tmux theme to $nord_path"
    git clone https://github.com/arcticicestudio/nord-tmux $nord_path
fi

# .tmux.conf
echo "Backing up existing ZSH config"
[ -f ~/.tmux.conf ] && mv ~/.tmux.conf ~/backups/dotfiles/.tmux.conf.backup.$(date +%Y-%m-%d)

echo "Updating tmux configuration"
cp $base_dir/tmux/.tmux.conf ~/.tmux.conf

# reload
echo "Reloading tmux"
tmux source-file ~/.tmux.conf
