#!/usr/bin/env bash

readonly base_dir=$(git rev-parse --show-toplevel)

echo "Setup Zsh"

echo "Install zsh"

if [[ ! -x "zsh" ]]
then
    echo "Could not find zsh executable"
    sudo apt-get install zsh
    sudo sh -c "echo $(which zsh) >> /etc/shells"
    sudo chsh -s $(which zsh)
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
else
    echo "Found zsh executable at $(which -a zsh)"
fi

ZSH_CUSTOM="/home/michael/.oh-my-zsh/custom"

echo "ZSH Custom directory: $ZSH_CUSTOM"

if [[ ! -d "$ZSH_CUSTOM/themes/spaceship-prompt" ]]
then
    echo "Installing spaceship theme"

    mkdir -p $ZSH_CUSTOM/themes/spaceship-prompy

    git clone https://github.com/spaceship-prompt/spaceship-prompt.git \
        "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1

    ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" \
        "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
else
    echo "Spaceship theme already exists"
fi

[ -f ~/.zshrc ] && mv ~/.zshrc ~/backups/dotfiles/.zshrc.backup.$(date +%Y-%m-%d)

echo "Copying zshrc to home directory"
cp $base_dir/zsh/.zshrc ~/.zshrc
