#!/usr/bin/env bash

# Install Clojure if it doesn't exist
if [[ ! -x clojure ]]; then
    echo "Installing clojure cli"
    curl -O https://download.clojure.org/install/linux-install-1.10.2.774.sh
    chmod +x linux-install-1.10.2.774.sh
    sudo ./linux-install-1.10.2.774.sh
    rm ./linux-install-1.10.2.774.sh
fi

# Backup the clojure dir if it exists
if [[ -d "~/.clojure" ]]; then
    mv ~/.clojure ~/.clojure.backup
fi

# Install the .clojure stuff
git clone git@github.com:admay/clojure-deps-edn.git ~/.clojure

# Install Clojure deps
echo "Installing Clojure deps"
clojure -P

# Print version
clojure --version

# Install clj kondo
curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
chmod +x install-clj-kondo
./install-clj-kondo
