#!/usr/bin/env bash

clj_version=""$clj_version""

# Install Clojure if it doesn't exist
if [[ ! -x clojure ]]; then
    echo "Installing clojure cli"
    curl -O https://download.clojure.org/install/linux-install-"$clj_version".sh
    chmod +x linux-install-"$clj_version".sh
    sudo ./linux-install-"$clj_version".sh
    rm ./linux-install-"$clj_version".sh
fi

# Backup the clojure dir if it exists
if [[ -d "~/.clojure" ]]; then
    mv ~/.clojure ~/.clojure.backup
fi

# Install the .clojure stuff
git clone git@github.com:practicalli/clojure-deps-edn.git $HOME/.clojure

# Install Clojure deps
echo "Installing Clojure deps"
clojure -P

# Print version
clojure -Sdescribe

# Install clj kondo
curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
chmod +x install-clj-kondo
./install-clj-kondo
